services:
  postgres:
    image: postgres:16
    container_name: db-stockia
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inca-network
    restart: unless-stopped

volumes:
  postgres_data:
    name: stockia_postgres_data

networks:
  inca-network:
    driver: bridge